// Generated by gencpp from file controlvehicle/joy_control_msg.msg
// DO NOT EDIT!


#ifndef CONTROLVEHICLE_MESSAGE_JOY_CONTROL_MSG_H
#define CONTROLVEHICLE_MESSAGE_JOY_CONTROL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controlvehicle
{
template <class ContainerAllocator>
struct joy_control_msg_
{
  typedef joy_control_msg_<ContainerAllocator> Type;

  joy_control_msg_()
    : sequence(0)
    , speed(0)
    , powerLR(0)  {
    }
  joy_control_msg_(const ContainerAllocator& _alloc)
    : sequence(0)
    , speed(0)
    , powerLR(0)  {
    }



   typedef uint8_t _sequence_type;
  _sequence_type sequence;

   typedef int8_t _speed_type;
  _speed_type speed;

   typedef int8_t _powerLR_type;
  _powerLR_type powerLR;




  typedef boost::shared_ptr< ::controlvehicle::joy_control_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controlvehicle::joy_control_msg_<ContainerAllocator> const> ConstPtr;

}; // struct joy_control_msg_

typedef ::controlvehicle::joy_control_msg_<std::allocator<void> > joy_control_msg;

typedef boost::shared_ptr< ::controlvehicle::joy_control_msg > joy_control_msgPtr;
typedef boost::shared_ptr< ::controlvehicle::joy_control_msg const> joy_control_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controlvehicle::joy_control_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controlvehicle::joy_control_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controlvehicle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'controlvehicle': ['/home/pi/catkin_ws/src/controlvehicle/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controlvehicle::joy_control_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controlvehicle::joy_control_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controlvehicle::joy_control_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "499cf4e3d592166be607da2914a0e4a0";
  }

  static const char* value(const ::controlvehicle::joy_control_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x499cf4e3d592166bULL;
  static const uint64_t static_value2 = 0xe607da2914a0e4a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controlvehicle/joy_control_msg";
  }

  static const char* value(const ::controlvehicle::joy_control_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 sequence\n\
int8 speed\n\
int8 powerLR\n\
";
  }

  static const char* value(const ::controlvehicle::joy_control_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
      stream.next(m.speed);
      stream.next(m.powerLR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct joy_control_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controlvehicle::joy_control_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controlvehicle::joy_control_msg_<ContainerAllocator>& v)
  {
    s << indent << "sequence: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sequence);
    s << indent << "speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "powerLR: ";
    Printer<int8_t>::stream(s, indent + "  ", v.powerLR);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLVEHICLE_MESSAGE_JOY_CONTROL_MSG_H
