// Generated by gencpp from file controlvehicle/Maxsonar.msg
// DO NOT EDIT!


#ifndef CONTROLVEHICLE_MESSAGE_MAXSONAR_H
#define CONTROLVEHICLE_MESSAGE_MAXSONAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controlvehicle
{
template <class ContainerAllocator>
struct Maxsonar_
{
  typedef Maxsonar_<ContainerAllocator> Type;

  Maxsonar_()
    : sonar1(0.0)
    , sonar2(0.0)
    , sonar3(0.0)
    , sonar4(0.0)  {
    }
  Maxsonar_(const ContainerAllocator& _alloc)
    : sonar1(0.0)
    , sonar2(0.0)
    , sonar3(0.0)
    , sonar4(0.0)  {
    }



   typedef float _sonar1_type;
  _sonar1_type sonar1;

   typedef float _sonar2_type;
  _sonar2_type sonar2;

   typedef float _sonar3_type;
  _sonar3_type sonar3;

   typedef float _sonar4_type;
  _sonar4_type sonar4;




  typedef boost::shared_ptr< ::controlvehicle::Maxsonar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controlvehicle::Maxsonar_<ContainerAllocator> const> ConstPtr;

}; // struct Maxsonar_

typedef ::controlvehicle::Maxsonar_<std::allocator<void> > Maxsonar;

typedef boost::shared_ptr< ::controlvehicle::Maxsonar > MaxsonarPtr;
typedef boost::shared_ptr< ::controlvehicle::Maxsonar const> MaxsonarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controlvehicle::Maxsonar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controlvehicle::Maxsonar_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controlvehicle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'controlvehicle': ['/home/pi/catkin_ws/src/controlvehicle/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controlvehicle::Maxsonar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controlvehicle::Maxsonar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controlvehicle::Maxsonar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controlvehicle::Maxsonar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controlvehicle::Maxsonar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controlvehicle::Maxsonar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controlvehicle::Maxsonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f513f8756037fca86f700a692eb93b6";
  }

  static const char* value(const ::controlvehicle::Maxsonar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f513f8756037fcaULL;
  static const uint64_t static_value2 = 0x86f700a692eb93b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::controlvehicle::Maxsonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controlvehicle/Maxsonar";
  }

  static const char* value(const ::controlvehicle::Maxsonar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controlvehicle::Maxsonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 sonar1\n\
float32 sonar2\n\
float32 sonar3\n\
float32 sonar4\n\
\n\
";
  }

  static const char* value(const ::controlvehicle::Maxsonar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controlvehicle::Maxsonar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sonar1);
      stream.next(m.sonar2);
      stream.next(m.sonar3);
      stream.next(m.sonar4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Maxsonar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controlvehicle::Maxsonar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controlvehicle::Maxsonar_<ContainerAllocator>& v)
  {
    s << indent << "sonar1: ";
    Printer<float>::stream(s, indent + "  ", v.sonar1);
    s << indent << "sonar2: ";
    Printer<float>::stream(s, indent + "  ", v.sonar2);
    s << indent << "sonar3: ";
    Printer<float>::stream(s, indent + "  ", v.sonar3);
    s << indent << "sonar4: ";
    Printer<float>::stream(s, indent + "  ", v.sonar4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLVEHICLE_MESSAGE_MAXSONAR_H
